input {
  file {
    path => "/logs/*"
    start_position => "beginning"
    codec => "json"
  }
}

output {
  elasticsearch {
    index => "ecommercelogs"
    hosts => ["ecommerce-elastic:9200"]
  }
}